# Generated by Django 6.0.5 on 2026-07-05 21:00

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='GH', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('voters_id', 'Voters ID'), ('drivers_license', 'Drivers License')], default='national_id', max_length=20),
        ),
    ]
