# Generated by Django 6.1.1 on 2026-10-02 13:58

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_cards/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='GH', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('voters_id', 'Voters ID'), ('drivers_license', 'Drivers License')], default='national_id', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
